# Generated by Django 5.2.8 on 2025-11-18 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('individuals', '0002_alter_individualcreditprofile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_type', models.CharField(choices=[('individual', 'Individual'), ('company', 'Company')], max_length=20)),
                ('requested_amount', models.BigIntegerField()),
                ('term_months', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('model_version', models.CharField(blank=True, max_length=128, null=True)),
                ('explanation', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_requests', to='companies.companycreditprofile')),
                ('individual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_requests', to='individuals.individualcreditprofile')),
            ],
            options={
                'verbose_name': 'Credit Request',
                'verbose_name_plural': 'Credit Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
