# Generated by Django 5.2.8 on 2025-11-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualCreditProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('yearly_income', models.FloatField()),
                ('existing_debt', models.FloatField()),
                ('collateral_value', models.FloatField()),
                ('risk_score', models.FloatField(blank=True, null=True)),
                ('explanation', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
