# Generated by Django 5.2.8 on 2025-11-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individuals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='individualcreditprofile',
            options={'verbose_name': 'Individual Credit Profile', 'verbose_name_plural': 'Individual Credit Profiles'},
        ),
        migrations.RemoveField(
            model_name='individualcreditprofile',
            name='explanation',
        ),
        migrations.RemoveField(
            model_name='individualcreditprofile',
            name='risk_score',
        ),
        migrations.AddField(
            model_name='individualcreditprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='individualcreditprofile',
            name='credit_history_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='individualcreditprofile',
            name='criminal_history',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='individualcreditprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='individualcreditprofile',
            name='guarantor_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='individualcreditprofile',
            name='kadastr_record',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='individualcreditprofile',
            name='model_version',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='individualcreditprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='individualcreditprofile',
            name='property_net_worth',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='individualcreditprofile',
            name='requested_amount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='individualcreditprofile',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='individualcreditprofile',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='individualcreditprofile',
            name='soliq_record',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='individualcreditprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='individualcreditprofile',
            name='term_months',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='individualcreditprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='individualcreditprofile',
            name='collateral_value',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='individualcreditprofile',
            name='existing_debt',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='individualcreditprofile',
            name='yearly_income',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
